version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: genai_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tools:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5433/genai_lms
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
  redis_data: